export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
echo "PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_CUDA_ALLOC_CONF"
export PYTHONPATH="$PYTHONPATH:$PWD/src"
echo "PYTHONPATH=$PYTHONPATH"
export CUDA_VISIBLE_DEVICES=0

# DATASET KITTI
DATASET=kitti
CONFIG_DIR="/home/eltons-pc/Configurations/v3/kitti_raw.txt" # KITTI

# DATASET DDAD
#DATASET=ddad
#CONFIG_DIR="/home/eltons-pc/Configurations/v3/ddad.txt" # DDAD


# (FEDSCDEPTH-KITTI) DISTRIBUTION = IID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = -1; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='15_11_2023_02:38:56'
#FEDERATION_ROUND=3
# (FEDSCDEPTH-KITTI-to-DDAD) DISTRIBUTION = IID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = -1; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='12_03_2024_21:55:48'
#FEDERATION_ROUND=10

# (BOFEDSCDEPTH-KITTI) DISTRIBUTION = IID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = 6; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='03_09_2023_13:07:11'
#FEDERATION_ROUND=3
# (BOFEDSCDEPTH-KITTI-to-DDAD) DISTRIBUTION = IID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = 6; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='13_03_2024_22:30:44'
#FEDERATION_ROUND=11

# (FEDSCDEPTH-DDAD) DISTRIBUTION = NIID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = -1; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='07_12_2023_00:00:26'
#FEDERATION_ROUND=3
# (FEDSCDEPTH-DDAD-to-KITTI) DISTRIBUTION = NIID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = -1; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='15_03_2024_11:22:23'
#FEDERATION_ROUND=9

# (BOFEDSCDEPTH-DDAD) DISTRIBUTION = NIID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = 6; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
#FEDERATED_MODEL_TIMESTAMP='09_10_2023_22:04:30'
#FEDERATION_ROUND=3
# (BOFEDSCDEPTH-DDAD-to-KITTI) DISTRIBUTION = NIID; TOTAL PARTICIPANTS = 12 ; PARTICIPANTS PER ROUND = 4 ; LOCAL EPOCHS = 3; SEARCH RANGE = 6; MAX LOCAL BATCHES TRAIN = 1000; MAX LOCAL BATCHES VAL = -1; MAX_ROUNDS = 36 ;
FEDERATED_MODEL_TIMESTAMP='17_03_2024_11:34:21'
FEDERATION_ROUND=11

# FEDERATED
PT="/home/eltons-pc/Logs/federated-sc-depth/$FEDERATED_MODEL_TIMESTAMP/round_$FEDERATION_ROUND/global_model_weights.pt"
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/federated/$FEDERATED_MODEL_TIMESTAMP/round_$FEDERATION_ROUND"
TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/federated_domain_adaptation/to_$DATASET/$FEDERATED_MODEL_TIMESTAMP/round_$FEDERATION_ROUND"

# CENTRALIZED KITTI
#CKPT=/home/eltons-pc/Logs/centralized_sc_depth/kitti/02_05_2023/last.ckpt
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/centralized/02_05_2023"

# CENTRALIZED DDAD
#CKPT=/home/eltons-pc/Logs/centralized_sc_depth/ddad/10_06_2023/last.ckpt
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/centralized/10_06_2023"

# CENTRALIZED KITTI to DDAD
#CKPT=/home/eltons-pc/Logs/centralized_sc_depth/kitti_to_ddad/11_03_2024/last.ckpt
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/centralized_domain_adaptation/$DATASET/02_05_2023"
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/centralized_domain_adaptation/$DATASET/11_03_2024"

# CENTRALIZED DDAD to KITTI
#CKPT=/home/eltons-pc/Logs/centralized_sc_depth/ddad_to_kitti/16_03_2024/last.ckpt
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/centralized_domain_adaptation/$DATASET/10_06_2023"
#TEST_OUTPUT_DIR="/home/eltons-pc/Logs/inferences/centralized_domain_adaptation/$DATASET/16_03_2024"

TEST_OUTPUT_LOG="$TEST_OUTPUT_DIR/test.log"

DATASET_DIR="/home/eltons-pc/Datasets/$DATASET"
TEST_INPUT_DIR=$DATASET_DIR/testing/color
TEST_GT_DIR=$DATASET_DIR/testing/depth
TEST_SEG_MASK=$DATASET_DIR/testing/seg_mask
DEPTH_PREDICTIONS_DIR="$TEST_OUTPUT_DIR/model_v3/depth"

python src/tests/test.py \
--config $CONFIG_DIR --dataset_dir $DATASET_DIR \
--ckpt_path "$CKPT" --pt_path "$PT"

python src/tests/inference.py --config $CONFIG_DIR \
--input_dir $TEST_INPUT_DIR --output_dir $TEST_OUTPUT_DIR \
--ckpt_path "$CKPT" --pt_path "$PT" \
--save-vis --save-depth

python src/tests/eval_depth.py \
--dataset $DATASET \
--pred_depth=$DEPTH_PREDICTIONS_DIR \
--gt_depth=$TEST_GT_DIR \
--seg_mask=$TEST_SEG_MASK > $TEST_OUTPUT_LOG

echo "Results saved at $TEST_OUTPUT_LOG"

